enyo.depends(
	"$lib/jquery.js",
	"$lib/bootstrap/js/bootstrap.js",
	"$lib/bootstrap/css/bootstrap.css",
	"$lib/bootstrap/css/bootstrap-responsive.css",
	"App.js",
	"Video.js",
	"Head.js",
	"Modal.js",
	"Input.js",
	"Progressbar.js",
	"Cues.js",
	"App.css",
	"Video.css"
);
